### ISSUE TITLE
API docker-compose defaults are not properly set

### ISSUE THREAD

**Issue by MarkRx** [capitalone/Hygieia#1207]
The current state of the docker-compose file results in exceptions when attempting to run API. See below. The docker-compose API should not default to requiring Jasypt. Right now it does because the docker image is build with "ENV SPRING_DATA_MONGODB_PASSWORD=ENC(aSPTk36yA/ZklUg75CrZ8w==)" which I presume is "password" encrypted with a key of "hygieiasecret".

The following should be done:
- There should be a way to run without Jasypt. Right now I can't start my collectors with docker-compose (without overriding commands) because the docker images do not have jasypt.encryptor.password. It seems this property is required even if I am not using ENC. It could be defaulted to "unencrypted" in the code perhaps.
- The 5 ENV commands in the Dockerfile should be removed. None of the other Dockerfiles contain these.
- ~~All of the other collectors should support automatically setting -Djasypt.encryptor.password if set using the same mechanism as the API.~~ The JASYPT_ENCRYPTOR_SECRET variable should be removed along with -Djasypt.encryptor.password=$JASYPT_ENCRYPTOR_SECRET. Spring will automatically set jasypt.encryptor.password if JASYPT_ENCRYPTOR_PASSWORD is set.
- Starting the jira collector requires the JASYPT_ENCRYPTOR_PASSWORD (equal to jasypt.encryptor.password) to be set to "hygieiasecret" even through I am not using ENC. Why?

```
hygieia-api:
  image: hygieia-api:latest
  container_name: hygieia-api
  ports:
  - "8080:8080"
  volumes:
  - ./logs:/hygieia/logs
  environment:
  - MONGO_PORT=tcp://10.0.2.2:27017
  - SPRING_DATA_MONGODB_DATABASE=dashboard
  - FEATURE_DYNAMIC_PIPELINE=enabled
```

> hygieia-api                               | Caused by: java.lang.IllegalArgumentException: Password cannot be set empty
> hygieia-api                               |     at org.jasypt.commons.CommonUtils.validateIsTrue(CommonUtils.java:150)
> hygieia-api                               |     at org.jasypt.encryption.pbe.StandardPBEByteEncryptor.resolveConfigurationPassword(StandardPBEByteEncryptor.java:792)
> hygieia-api                               |     at org.jasypt.encryption.pbe.StandardPBEByteEncryptor.cloneAndInitializeEncryptor(StandardPBEByteEncryptor.java:486)
> hygieia-api                               |     at org.jasypt.encryption.pbe.StandardPBEStringEncryptor.cloneAndInitializeEncryptor(StandardPBEStringEncryptor.java:469)
> hygieia-api                               |     at org.jasypt.encryption.pbe.PooledPBEStringEncryptor.initialize(PooledPBEStringEncryptor.java:392)
> hygieia-api                               |     at org.jasypt.encryption.pbe.PooledPBEStringEncryptor.decrypt(PooledPBEStringEncryptor.java:489)
> hygieia-api                               |     at com.ulisesbocchio.jasyptspringboot.encryptor.LazyStringEncryptor.decrypt(LazyStringEncryptor.java:32)
> hygieia-api                               |     at org.jasypt.properties.PropertyValueEncryptionUtils.decrypt(PropertyValueEncryptionUtils.java:72)
> hygieia-api                               |     at com.ulisesbocchio.jasyptspringboot.EncryptablePropertySource.getProperty(EncryptablePropertySource.java:19)
> hygieia-api                               |     at com.ulisesbocchio.jasyptspringboot.wrapper.EncryptableMapPropertySourceWrapper.getProperty(EncryptableMapPropertySourceWrapper.java:28)
> hygieia-api                               |     at org.springframework.boot.bind.PropertySourcesPropertyValues.getEnumerableProperty(PropertySourcesPropertyValues.java:140)
> hygieia-api                               |     at org.springframework.boot.bind.PropertySourcesPropertyValues.processEnumerablePropertySource(PropertySourcesPropertyValues.java:124)
> hygieia-api                               |     at org.springframework.boot.bind.PropertySourcesPropertyValues.processPropertySource(PropertySourcesPropertyValues.java:106)
> hygieia-api                               |     at org.springframework.boot.bind.PropertySourcesPropertyValues.<init>(PropertySourcesPropertyValues.java:94)
> hygieia-api                               |     at org.springframework.boot.bind.PropertiesConfigurationFactory.getPropertyValues(PropertiesConfigurationFactory.java:281)
> hygieia-api                               |     at org.springframework.boot.bind.PropertiesConfigurationFactory.doBindPropertiesToTarget(PropertiesConfigurationFactory.java:252)
> hygieia-api                               |     at org.springframework.boot.bind.PropertiesConfigurationFactory.bindPropertiesToTarget(PropertiesConfigurationFactory.java:227)
> hygieia-api                               |     at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:296)
> hygieia-api                               |     ... 50 more
> hygieia-api exited with code 1

If I add a JASYPT_ENCRYPTOR_SECRET and set the JASYPT_ENTRYPTOR_SECRET:

```
hygieia-api:
  image: hygieia-api:latest
  container_name: hygieia-api
  ports:
  - "8080:8080"
  volumes:
  - ./logs:/hygieia/logs
  environment:
  - JASYPT_ENCRYPTOR_SECRET=mysecret
  - MONGO_PORT=tcp://10.0.2.2:27017
  - SPRING_DATA_MONGODB_DATABASE=dashboard
  - FEATURE_DYNAMIC_PIPELINE=enabled
```

> hygieia-api                               | Caused by: com.ulisesbocchio.jasyptspringboot.exception.DecryptionException: Decryption of Properties failed,  make sure encryption/decryption passwords match
> hygieia-api                               |     at com.ulisesbocchio.jasyptspringboot.EncryptablePropertySource.getProperty(EncryptablePropertySource.java:21)
> hygieia-api                               |     at com.ulisesbocchio.jasyptspringboot.wrapper.EncryptableMapPropertySourceWrapper.getProperty(EncryptableMapPropertySourceWrapper.java:28)
> hygieia-api                               |     at org.springframework.boot.bind.PropertySourcesPropertyValues.getEnumerableProperty(PropertySourcesPropertyValues.java:140)
> hygieia-api                               |     at org.springframework.boot.bind.PropertySourcesPropertyValues.processEnumerablePropertySource(PropertySourcesPropertyValues.java:124)
> hygieia-api                               |     at org.springframework.boot.bind.PropertySourcesPropertyValues.processPropertySource(PropertySourcesPropertyValues.java:106)
> hygieia-api                               |     at org.springframework.boot.bind.PropertySourcesPropertyValues.<init>(PropertySourcesPropertyValues.java:94)
> hygieia-api                               |     at org.springframework.boot.bind.PropertiesConfigurationFactory.getPropertyValues(PropertiesConfigurationFactory.java:281)
> hygieia-api                               |     at org.springframework.boot.bind.PropertiesConfigurationFactory.doBindPropertiesToTarget(PropertiesConfigurationFactory.java:252)
> hygieia-api                               |     at org.springframework.boot.bind.PropertiesConfigurationFactory.bindPropertiesToTarget(PropertiesConfigurationFactory.java:227)
> hygieia-api                               |     at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:296)
> hygieia-api                               |     ... 50 more

This works because of the default value of SPRING_DATA_MONGODB_PASSWORD in the docker image:

```
hygieia-api:
  image: hygieia-api:latest
  container_name: hygieia-api
  ports:
  - "8080:8080"
  volumes:
  - ./logs:/hygieia/logs
  environment:
  - JASYPT_ENCRYPTOR_SECRET=hygieiasecret
  - MONGO_PORT=tcp://10.0.2.2:27017
  - SPRING_DATA_MONGODB_DATABASE=dashboard
  - FEATURE_DYNAMIC_PIPELINE=enabled
```
