### ISSUE TITLE
Hygieia Jenkins Plugin: 500 when testing the API connection

### ISSUE THREAD

**Issue by guillermonoainquantion** [capitalone/Hygieia#1220]
I am running Jenkins and Hygieia in a docker compose setup. The dashboard is fully functional, with UI and API communicating correctly through `http://hygieia-api:8080/api`. However, when I configure the Jenkins plugin using this same URL and test the connection, I get a 500 with `A RequestDispatcher could not be located for the default servlet 'api'`.

I assume that means that I can reach the API server from Jenkins, but I can't guess much more...

**Comment by satishc1** [comment]
@guillermonoainquantion  Open a browser and and go to http://hygieia-api:8080/api/ping  . What's the output you see ?  Also click Apply before doing a "Test connection" in jenkins plugin section.

**Comment by guillermonoainquantion** [comment]
I made a `curl http://hygieia-api:8080/api/ping` from inside the Jenkins container and got the following (somehow expected) result.
```
{"timestamp":1488537717937,"status":500,"error":"Internal Server Error","exception":"java.lang.IllegalStateException","message":"A RequestDispatcher could not be located for the default servlet 'api'","path":"/api/ping"}
```

I already found out about the Apply before "Test Connection", so I'm afraid it won't be that either :(

**Comment by satishc1** [comment]
@guillermonoainquantion What port is jenkins running on inside your container? Can you post your yml file ?

**Comment by guillermonoainquantion** [comment]
Jenkins is running in port 8080 and it is not exposed outside the container, as I have nginx in front.

The relevant docker-compose.yml parts are:

```yml
version: '2'
services:
  nginx:
    image: "nginx:latest"
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      cinet:
        ipv4_address: 10.10.1.20
    depends_on:
      - hygieia-ui
      - sonarqube
      - jenkins
    volumes:
      - ./data_nginx:/etc/nginx/conf.d:ro
  jenkins:
    build:
      context: ./dockerfiles/jenkins
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    container_name: jenkins
    networks:
      - cinet
    privileged: true
    volumes:
      - ./data_jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    environment:
      DOCKER_SOCKET: /var/run/docker.sock
      DOCKER_GROUP: dockerhost
      JENKINS_USER: jenkins
      DOCKER_HOST: unix:///var/run/docker.sock
      http_proxy: ****
      https_proxy: ****
      no_proxy: ****
      JAVA_OPTS: ##Proxy setup here

  mongodb:
    image: mongo:latest
    container_name: hygieia-db
    command: mongod --smallfiles
    networks:
      - cinet
    volumes:
      - ./data_hygieia/mongo:/data/db:rw
  hygieia-api:
    image: capitaloneio/hygieia-api:latest
    container_name: hygieia-api
    networks:
      - cinet
    volumes:
      - ./data_hygieia/logs:/hygieia/logs
    depends_on:
      - mongodb
    links:
      - mongodb:mongo
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: dashboard
      SPRING_DATA_MONGODB_USERNAME: mongo
      SPRING_DATA_MONGODB_PASSWORD: ******
  hygieia-ui:
    image: capitaloneio/hygieia-ui:latest
    container_name: hygieia-ui
    networks:
      - cinet
    depends_on:
      - hygieia-api
    environment:
      HYGIEIA_API_PORT: http://hygieia-api:8080
networks:
  cinet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.1.0/25
          gateway: 10.10.1.1

```
