### ISSUE TITLE
Compose file - Error in repository name

### ISSUE THREAD

**Issue by yakhyadabo** [capitalone/Hygieia#1375]
This is the output I have when running the compose file : 

> docker-compose -f compose.yml up
> Pulling hygieia-api (hygieia-api:latest)...
> ERROR: repository hygieia-api not found: does not exist or no pull access
> make: *** [up] Error 1

I have to add the repository **capitalone** to make it work. capitalone/hygieia-api:latest. 

Can you please confirm if it's the right way to run the compose project ?

**Comment by yakhyadabo** [comment]
I'm trying to setup the compose project, but it fails. 
Here's the stacktrace: 
```

hygieia-api    | Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serverProperties': Could not bind properties to [unknown] (target=server, ignoreInvalidFields=false, ignoreUnknownFields=false, ignoreNestedProperties=false); nested exception is java.lang.IllegalArgumentException: Password cannot be set empty
hygieia-api    |        at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:303)
hygieia-api    |        at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:250)
hygieia-api    |        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
hygieia-api    |        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1566)
hygieia-api    |        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
hygieia-api    |        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
hygieia-api    |        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
hygieia-api    |        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
hygieia-api    |        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
hygieia-api    |        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
hygieia-api    |        at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1120)
hygieia-api    |        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1044)
hygieia-api    |        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:942)
hygieia-api    |        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:533)
hygieia-api    |        ... 37 more
hygieia-api    | Caused by: java.lang.IllegalArgumentException: Password cannot be set empty
hygieia-api    |        at org.jasypt.commons.CommonUtils.validateIsTrue(CommonUtils.java:150)
hygieia-api    |        at org.jasypt.encryption.pbe.StandardPBEByteEncryptor.resolveConfigurationPassword(StandardPBEByteEncryptor.java:792)
hygieia-api    |        at org.jasypt.encryption.pbe.StandardPBEByteEncryptor.cloneAndInitializeEncryptor(StandardPBEByteEncryptor.java:486)
hygieia-api    |        at org.jasypt.encryption.pbe.StandardPBEStringEncryptor.cloneAndInitializeEncryptor(StandardPBEStringEncryptor.java:469)
hygieia-api    |        at org.jasypt.encryption.pbe.PooledPBEStringEncryptor.initialize(PooledPBEStringEncryptor.java:392)
hygieia-api    |        at org.jasypt.encryption.pbe.PooledPBEStringEncryptor.decrypt(PooledPBEStringEncryptor.java:489)
hygieia-api    |        at com.ulisesbocchio.jasyptspringboot.encryptor.LazyStringEncryptor.decrypt(LazyStringEncryptor.java:32)
hygieia-api    |        at org.jasypt.properties.PropertyValueEncryptionUtils.decrypt(PropertyValueEncryptionUtils.java:72)

```

**Comment by nitin1706** [comment]
@yakhyadabo : can you share your properties file. 
if there is no password, maybe you can try with commenting password

**Comment by yakhyadabo** [comment]
Here's the compose file : 
```

mongodb:
  image: mongo:latest
  container_name: mongodb
  command: mongod --smallfiles
  ports:
    - "27017:27017"
      #  volumes:
      #    - ./mongo:/data/db:rw
      #  volume_driver: local


hygieia-api:
  image: capitalone/hygieia-api:latest
  container_name: hygieia-api
  ports:
    - "8080:8080"
      #  volumes:
      #    - ./logs:/hygieia/logs
  links:
    - mongodb:mongo
  environment:
    - jasypt.encryptor.password=hygieiasecret


hygieia-ui:
  image: capitalone/hygieia-ui:latest
  container_name: hygieia-ui
  ports:
    - "8088:80"
  links:
    - hygieia-api
```

**Comment by asg247** [comment]
@yakhyadabo please retry with the below configuration

```
mongodb:
  image: mongo:latest
  container_name: mongodb
  command: mongod --smallfiles
  ports:
    - "27017:27017"
      #  volumes:
      #    - ./mongo:/data/db:rw
      #  volume_driver: local


hygieia-api:
  image: capitalone/hygieia-api:latest
  container_name: hygieia-api
  ports:
  - "8080:8080"
  volumes:
  - ./logs:/hygieia/logs
  links:
  - mongodb:mongo
  environment:
  - SPRING_DATA_MONGODB_DATABASE=dashboarddb
  - SPRING_DATA_MONGODB_HOST=10.116.224.92
  - SPRING_DATA_MONGODB_PORT=27017
  - SPRING_DATA_MONGODB_USERNAME=dashboarduser
  - SPRING_DATA_MONGODB_PASSWORD=ENC(dMK9gBJcGIe0Qupi3HYKvkcOQowpU4iY)
  - AUTH_EXPIRATION_TIME=360000
  - AUTH_SECRET=secret
  
hygieia-ui:
  image: capitalone/hygieia-ui:latest
  container_name: hygieia-ui
  ports:
  - "8088:80"
  links:
  - hygieia-api
```
