### ISSUE TITLE
401 unauthorized when creating a dashboard. 

### ISSUE THREAD

**Issue by anutting** [capitalone/Hygieia#1707]
response: {
"timestamp":1504626172545,
"status":401,
"error":"Unauthorized",
"message":"Full authentication is required to access this resource",
"path":"/api/dashboard"
} 

Docker-compose.yml
```
mongodb:
  image: mongo:latest
  environment:
    - MONGODB_USERNAME=dashboarduser
    - MONGODB_DATABASE=dashboarddb
    - MONGODB_PASSWORD=1qazxSw2

hygieia-api:
  image: hygieia-api:latest
  container_name: hygieia-api
  volumes:
  - ./logs:/hygieia/logs
  environment:
    - jasypt.encryptor.password=hygieiasecret
    - SPRING_DATA_MONGODB_DATABASE=dashboarddb
    - SPRING_DATA_MONGODB_HOST=mongo
    - SPRING_DATA_MONGODB_PORT=27017
    - SPRING_DATA_MONGODB_USERNAME=dashboarduser
    - SPRING_DATA_MONGODB_PASSWORD=1qazxSw2
    - AUTH_AUTHENTICATION_PROVIDERS=STANDARD
    - AUTH_EXPIRATION_TIME=3600
    - AUTH_SECRET=hygieiasecret
    - CONTEXT_PATH=/api
  links:
  - mongodb:mongo

hygieia-ui:
  image: hygieia-ui:latest
  container_name: hygieia-ui
  ports:
  - "8088:80"
  links:
  - hygieia-api
```

Once logged in as a standard user, I go to create a dashboard, then get the error underneath the title: "Error creating dashboard. Changed title and try again." Developer tools show the response above for the request sent.

any ideas how to fix this?

**Comment by nitin1706** [comment]
can you try creating dashboard by logging in again. I have seen similar issue and found that it was something due to user session. This was resolved for me once I logged in again.

**Comment by anutting** [comment]
I just logged out, cleared cache, then logged back in and attempted to create a dashboard and I still received the same response. I've restarted all of the containers as well. I'm thinking there's a configuration issue, but unfortunately this error isn't output to the api console or the log.

**Comment by nitin1706** [comment]
can you share screenshot of error. if error is not showing in api logs, maybe it is validation error.

**Comment by anutting** [comment]
Here's a screenshot of the UI after I attempt to make a dashboard:

![screen shot 2017-09-05 at 1 59 17 pm](https://user-images.githubusercontent.com/21373974/30075283-7efdbe34-9242-11e7-9e0a-c25e35522665.png)

**Comment by nireeshT** [comment]
@anutting  - share api prop file and api log

**Comment by nireeshT** [comment]
@anutting  did you try changing title and save ?

**Comment by anutting** [comment]
Since I'm using docker-compose, the api properties are set in the docker-compose.yml pasted above. It's my understanding that the properties file is created using the properties-builder.sh. 

The api log is attached in a txt file. Thank you for taking the time to troubleshoot this error.
[api-log.txt](https://github.com/capitalone/Hygieia/files/1278464/api-log.txt)

**Comment by anutting** [comment]
Yes, I've tried several different titles as well.

**Comment by nitin1706** [comment]
do you see API connectivity is successful on Login screen?

**Comment by anutting** [comment]
yes I see API CONNECTIVITY with a green checkmark and 2.0.5-SNAPSHOT

**Comment by anutting** [comment]
It's odd. Sometimes when I click create, the "Create a new dashboard" modal stays visible, but the background page is now Login.

**Comment by anutting** [comment]
I see the authentication errors on the log, but those must be from a previous executions. Here's a fresh log after a docker-compose start and 1 attempt to create a dashboard.
[api-log.txt](https://github.com/capitalone/Hygieia/files/1278530/api-log.txt)

**Comment by nitin1706** [comment]
I see some exceptions in this log, this as first exception:

`2017-09-05 18:46:11,760 INFO  o.s.w.s.m.m.a.RequestMappingHandlerMapping - Mapped "{[/registerUser],methods=[POST],consumes=[application/json],produces=[application/json]}" onto public org.springframework.http.ResponseEntity<java.lang.Void> com.capitalone.dashboard.rest.AuthenticationController.registerUser(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse,com.capitalone.dashboard.request.AuthenticationRequest) throws java.io.IOException,javax.servlet.ServletException`

can you share what properties it is using.

**Comment by anutting** [comment]
I'm not entirely sure where to place my properties file since there is a properties-builder in the api/docker directory. I've been changing properties in the docker-compose.yml with some success:
```
mongodb:
  image: mongo:latest
  environment:
    - MONGODB_USERNAME=dashboarduser
    - MONGODB_DATABASE=dashboarddb
    - MONGODB_PASSWORD=1qazxSw2

hygieia-api:
  image: hygieia-api:latest
  container_name: hygieia-api
  volumes:
  - ./logs:/hygieia/logs
  environment:
    - jasypt.encryptor.password=hygieiasecret
    - SPRING_DATA_MONGODB_DATABASE=dashboarddb
    - SPRING_DATA_MONGODB_HOST=mongo
    - SPRING_DATA_MONGODB_PORT=27017
    - SPRING_DATA_MONGODB_USERNAME=dashboarduser
    - SPRING_DATA_MONGODB_PASSWORD=1qazxSw2
    - AUTH_AUTHENTICATION_PROVIDERS=STANDARD
    - AUTH_EXPIRATION_TIME=3600
    - AUTH_SECRET=hygieiasecret
    - CONTEXT_PATH=/api
  links:
  - mongodb:mongo

hygieia-ui:
  image: hygieia-ui:latest
  container_name: hygieia-ui
  ports:
  - "8088:80"
  links:
  - hygieia-api
```
