### ISSUE TITLE
How to make the API work in the same network than  docker ? 

### ISSUE THREAD

**Issue by samyzemmouri** [capitalone/Hygieia#1825]
for example if docker is  running  in 172.18.0.1

how  could i set the api to 172.18.0.1:8080/api...

in the  jenkins i saw that you have settings.getDockerLocalHostIP() but it's always  empty 

Thank you

**Comment by pversteijnen** [comment]
I ran into this issue that the UI could not connect to the API. What worked for me was in the UI configuring set the API with my external IP address. Some how this solved my issue of not connecting to the API (using Docker-Compose)
```
  # Hygieia UI layer
  hygieia-ui:
    image: pversteijnen/hygieia-ui
    container_name: hygieia-ui
    environment:
      - jasypt.encryptor.password=hygieiasecret
      - API_HOST=<your external IP>
      - API_PORT=8080
    ports:
      - "8090:80"
    links:
      - hygieia-api
```
