### ISSUE TITLE
docker Jira Endless Loop: StoryDataClientImpl 

### ISSUE THREAD

**Issue by DimsumPanda** [capitalone/Hygieia#1895]
Before I added the JIRA_PAGE_SIZE=10, I was gettting a socket timeout error. However, when I added this environment variable, it goes in an endless loop through pages 10 by 10 and the data is still not populated in the dashboard.

```
hygieia-jira     | 2017-12-08 16:11:00,012 INFO  c.c.d.collector.CollectorTask - ------------------------------- ----
hygieia-jira     | 2017-12-08 16:11:00,013 INFO  c.c.d.collector.CollectorTask - https://{mycompany}/jira
hygieia-jira      | 2017-12-08 16:11:00,013 INFO  c.c.d.collector.CollectorTask - ------------------------------- ----
hygieia-jira      | 2017-12-08 16:11:00,027 INFO  c.c.d.collector.CollectorTask - Team Data               0         0s
hygieia-jira      | 2017-12-08 16:11:01,739 INFO  c.c.d.collector.CollectorTask - Project Data           62         1s
hygieia-jira      | 2017-12-08 16:11:06,617 INFO  c.c.d.c.story.StoryDataClientImpl - Loop i 0 pageSize 10
hygieia-jira      | 2017-12-08 16:11:10,339 INFO  c.c.d.c.story.StoryDataClientImpl - Loop i 10 pageSize 10

```
My docker-compose:
```
hygieia-jira-feature-collector:
  image: hygieia-jira-feature-collector:latest
  container_name: hygieia-jira
  links:
  - mongodb
  - hygieia-api
  environment:
  - JIRA_BASE_URL=https://{mycompany}.com/jira
  - JIRA_CREDENTIALS={base64Credentials}
  - JIRA_ISSUE_TYPE_NAMES=Story
  - MONGO_PORT=tcp://mongodb:27017
  - JIRA_PAGE_SIZE=10
```
![jiraissue](https://user-images.githubusercontent.com/10524720/33778722-f71c3552-dc17-11e7-9a6d-f472819f97c4.JPG)
