### ISSUE TITLE
hygieia api connect issues

### ISSUE THREAD

**Issue by superkunkun** [capitalone/Hygieia#1962]
Hi, Guys
I met the API connectivity issues when I try to start the hygieia service.
I use the http://localhost:3000/ and cannot login because of the API connective cannot buildup.
when I use http://localhost:8080/api/ping ,it return ture. 
Can some guys help me on this issues ?

**Comment by Sbrenthughes** [comment]
Are you able to get the login screen just not the green check mark?

**Comment by superkunkun** [comment]
Hi, Sbrenthughes
Sure, I can access the login butthon but the API connectivity green check is unavailable .

**Comment by Sbrenthughes** [comment]
Can you check to see if you UI is trying to connection to the api on port 8080?

**Comment by superkunkun** [comment]
Hi，Sbrenthughes
how can I check this , can I get some logs or other information.

**Comment by Sbrenthughes** [comment]
Can you post what errors are in the console of the UI when navigate to the login page? If you have changed anything then it defaults to 8080.

**Comment by pversteijnen** [comment]
I also ran into this issue before. What worked for me was in the UI configuring set the API with my external IP address. Some how this solved my issue of not connecting to the API (using Docker-Compose)

```
  # Hygieia UI layer
  hygieia-ui:
    image: pversteijnen/hygieia-ui
    container_name: hygieia-ui
    environment:
      - jasypt.encryptor.password=hygieiasecret
      - API_HOST=<your external IP>
      - API_PORT=8080
    ports:
      - "8090:80"
    links:
      - hygieia-api
```
