### ISSUE TITLE
mongodb install error - Unrecognized option: storage

### ISSUE THREAD

**Issue by sakthiom2014** [capitalone/Hygieia#743]
C:\dashboard>"C:\dashboard\mongodb-win32-x86_64-3.2.1\bin\mongod.exe" --config "C:\dashboard\mongodb\mongod.cfg" -install
Unrecognized option: storage
try 'C:\dashboard\mongodb-win32-x86_64-3.2.1\bin\mongod.exe --help' for more information

**Comment by mrpudn** [comment]
hmm, you probably have something in your `mongod.cfg` file that the MongoDB daemon doesn't like - I would check there for the `storage` option

**Comment by tabladrum** [comment]
Can you paste the monod.cfg content?

**Comment by sakthiom2014** [comment]
systemLog:
destination: file
path: C:\dashboard\data\log\mongod.log
storage:
dbPath: C:\dashboard\data\db


C:\dashboard>"C:\dashboard\mongodb\mongodb-win32-x86_64-3.2.1\bin\mongod.exe" --config "C:\dashboard\mongodb\mongod.cfg" -install
Unrecognized option: storage
try 'C:\dashboard\mongodb\mongodb-win32-x86_64-3.2.1\bin\mongod.exe --help' for more information

**Comment by mrpudn** [comment]
Make sure the spacing is correct:
```yaml
systemLog:
  destination: file
  path: C:\dashboard\data\log\mongod.log
storage:
  dbPath: C:\dashboard\data\db
```

Here's mine, for reference:
```yaml
systemLog:
  destination: file
  path: /usr/local/var/log/mongodb/mongo.log
  logAppend: true
storage:
  dbPath: /usr/local/var/mongodb
net:
  bindIp: 127.0.0.1
```

Obviously, your paths will be different.
